import type { Metadata } from "next";
import { Kanit, Poppins } from "next/font/google";
import "./globals.css";
import { FadeTransition } from "@/components/animation/FadeTransition";
import { Footer } from "@/components/footer";

// นำเข้า font ที่ต้องการ
const kanit = Kanit({
	variable: "--font-kanit",
	subsets: ["thai"],
	weight: ["400", "700"], // เลือกน้ำหนักของ font
});

const poppins = Poppins({
	variable: "--font-poppins",
	subsets: ["latin"],
	weight: ["400", "700"], // เลือกน้ำหนักของ font
});

export const metadata: Metadata = {
	title: "NYC ITSM",
	description: "Generated by Q",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${kanit.variable} ${poppins.variable} antialiased`}>
				<FadeTransition>{children}</FadeTransition>
				<Footer />
			</body>
		</html>
	);
}
